export const movieTitles: string[] = [
  'Focus',
  '1917',
  'Kandahar',
  'It',
  'Plane',
  'Terrifier',
  'Interstellar',
  'Mad Max: Fury Road',
  'Parasite',
  'Avengers: Endgame',
  'The Matrix',
  'Gladiator',
  'The Lord of the Rings: The Return of the King',
  'Jurassic Park',
  'Fight Club',
  'The Lion King',
  'Forrest Gump',
  'The Avengers',
  'The Prestige',
  'The Dark Knight Rises',
  'The Social Network',
  'The Departed',
  'Shutter Island',
  'Whiplash',
  'The Revenant',
  'Inglourious Basterds',
  'The Godfather: Part II',
  'The Silence of the Lambs',
  'A Clockwork Orange',
  "Schindler's List",
  'Memento',
  'Se7en',
  'Goodfellas',
  'Catch Me If You Can',
  'The Wolf of Wall Street',
  'Citizen Kane',
  'The Green Mile',
  'The Matrix Reloaded',
  '12 Angry Men',
  'No Country for Old Men',
  'Django Unchained',
  'Blade Runner 2049',
  'Spider-Man: No Way Home',
  'Avengers: Infinity War',
  'The Incredibles',
  'San Andreas',
  'The Truman Show',
  'Oldboy',
];
